const { Survivor } = require("./Survivor")
// const { SkillTree } = require("./SkillTree")
const { Gear } = require("./Gear")
const { Zombie } = require("./Zombie")


let brena = new Survivor ("brena")
console.log(Survivor.allSurvivors)
let raquel = new Survivor("raquel")
console.log(Survivor.allSurvivors)
console.log("--------------")
console.log(brena.isAlive())
console.log("--------------")
console.log(brena.isHarmed())
console.log(brena.isHarmed())
console.log(brena.isHarmed())
console.log("--------------")
console.log(brena.isAlive())
console.log(Survivor.allSurvivors)
console.log("--------------")
let brenaGear = new Gear
brenaGear.addGear('baseball bat')
console.log(brenaGear.gear)
console.log("--------------")